import './globals.css'
import type { Metadata } from 'next'
import { Schibsted_Grotesk } from 'next/font/google'

const schibsted_Grotesk = Schibsted_Grotesk({ 
  subsets: ['latin'],  
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={schibsted_Grotesk.className}>{children}</body>
    </html>
  )
}
